apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    nameOverride: ingress-nginx
    fullnameOverride: ingress-nginx
    controller:
      admissionWebhooks:
        service:
          ipFamilyPolicy: SingleStack
      containerName: controller
      hostPort:
        enabled: false
      ingressClassResource:
        default: true
      service:
        enabled: true